// <auto-generated />
using System;
using System.Collections.Generic;
using HotelBooking.Modules.Property.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HotelBooking.Modules.Property.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PropertyDbContext))]
    [Migration("20260720133939_AddRoomTypePersistence")]
    partial class AddRoomTypePersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("property")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HotelBooking.Modules.Property.Domain.Hotels.Hotel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultLanguage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("default_language");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("SellingCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("selling_currency")
                        .IsFixedLength();

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.Property<int?>("StarRating")
                        .HasColumnType("integer")
                        .HasColumnName("star_rating");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("time_zone_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Address", "HotelBooking.Modules.Property.Domain.Hotels.Hotel.Address#Address", b1 =>
                        {
                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_city");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_country_code");

                            b1.Property<string>("DetailAddress")
                                .HasColumnType("text")
                                .HasColumnName("address_detail");

                            b1.Property<string>("PostalCode")
                                .HasColumnType("text")
                                .HasColumnName("address_postal_code");

                            b1.Property<string>("Region")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_region");

                            b1.Property<string>("StreetAddress")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_street");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "CheckInPolicy", "HotelBooking.Modules.Property.Domain.Hotels.Hotel.CheckInPolicy#CheckInPolicy", b1 =>
                        {
                            b1.Property<bool>("AllowsEarlyCheckIn")
                                .HasColumnType("boolean")
                                .HasColumnName("allows_early_check_in");

                            b1.Property<bool>("AllowsLateCheckOut")
                                .HasColumnType("boolean")
                                .HasColumnName("allows_late_check_out");

                            b1.Property<TimeOnly>("CheckInFrom")
                                .HasColumnType("time without time zone")
                                .HasColumnName("check_in_from");

                            b1.Property<TimeOnly?>("CheckInUntil")
                                .HasColumnType("time without time zone")
                                .HasColumnName("check_in_until");

                            b1.Property<TimeOnly>("CheckOutUntil")
                                .HasColumnType("time without time zone")
                                .HasColumnName("check_out_until");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ContactInfo", "HotelBooking.Modules.Property.Domain.Hotels.Hotel.ContactInfo#ContactInfo", b1 =>
                        {
                            b1.Property<string>("Email");

                            b1.Property<string>("Phone");

                            b1.Property<string>("Website");

                            b1
                                .ToJson("contact_info")
                                .HasColumnType("jsonb");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "GeoLocation", "HotelBooking.Modules.Property.Domain.Hotels.Hotel.GeoLocation#GeoLocation", b1 =>
                        {
                            b1.Property<decimal>("Latitude")
                                .HasColumnType("numeric")
                                .HasColumnName("latitude");

                            b1.Property<decimal>("Longitude")
                                .HasColumnType("numeric")
                                .HasColumnName("longitude");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "HotelPolicy", "HotelBooking.Modules.Property.Domain.Hotels.Hotel.HotelPolicy#HotelPolicy", b1 =>
                        {
                            b1.Property<bool>("AllowsChildren")
                                .HasColumnType("boolean")
                                .HasColumnName("allows_children");

                            b1.Property<bool>("AllowsPets")
                                .HasColumnType("boolean")
                                .HasColumnName("allows_pets");

                            b1.Property<bool>("AllowsSmoking")
                                .HasColumnType("boolean")
                                .HasColumnName("allows_smoking");

                            b1.Property<int?>("MinimumCheckInAge")
                                .HasColumnType("integer")
                                .HasColumnName("minimum_check_in_age");

                            b1.Property<bool>("RequiresDeposit")
                                .HasColumnType("boolean")
                                .HasColumnName("requires_deposit");
                        });

                    b.HasKey("Id")
                        .HasName("pk_hotels");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_hotels_slug");

                    b.ToTable("hotels", "property");
                });

            modelBuilder.Entity("HotelBooking.Modules.Property.Domain.RoomTypes.RoomType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uuid")
                        .HasColumnName("hotel_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Occupancy", "HotelBooking.Modules.Property.Domain.RoomTypes.RoomType.Occupancy#Occupancy", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("MaxAdults")
                                .HasColumnType("integer")
                                .HasColumnName("max_adults");

                            b1.Property<int>("MaxChildren")
                                .HasColumnType("integer")
                                .HasColumnName("max_children");

                            b1.Property<int>("MaxOccupancy")
                                .HasColumnType("integer")
                                .HasColumnName("max_occupancy");
                        });

                    b.HasKey("Id")
                        .HasName("pk_room_types");

                    b.HasIndex("HotelId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_room_types_hotel_id_code");

                    b.ToTable("room_types", "property", t =>
                        {
                            t.HasCheckConstraint("ck_room_types_occupancy_valid", "max_adults >= 1 AND max_children >= 0 AND max_occupancy >= 1 AND max_adults <= max_occupancy AND max_children <= max_occupancy AND max_occupancy <= max_adults + max_children");
                        });
                });

            modelBuilder.Entity("HotelBooking.Modules.Property.Domain.RoomTypes.RoomType", b =>
                {
                    b.HasOne("HotelBooking.Modules.Property.Domain.Hotels.Hotel", null)
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_room_types_hotels_hotel_id");

                    b.OwnsMany("HotelBooking.Modules.Property.Domain.RoomTypes.ValueObjects.BedComposition", "_bedCompositions", b1 =>
                        {
                            b1.Property<long>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<long>("id"));

                            b1.Property<string>("BedType")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("bed_type");

                            b1.Property<int>("Quantity")
                                .HasColumnType("integer")
                                .HasColumnName("quantity");

                            b1.Property<Guid>("room_type_id")
                                .HasColumnType("uuid");

                            b1.HasKey("id")
                                .HasName("pk_room_type_bed_compositions");

                            b1.HasIndex("room_type_id")
                                .HasDatabaseName("ix_room_type_bed_compositions_room_type_id");

                            b1.ToTable("room_type_bed_compositions", "property", t =>
                                {
                                    t.HasCheckConstraint("ck_room_type_bed_compositions_quantity_positive", "quantity >= 1");
                                });

                            b1.WithOwner()
                                .HasForeignKey("room_type_id")
                                .HasConstraintName("fk_room_type_bed_compositions_room_types_room_type_id");
                        });

                    b.Navigation("_bedCompositions");
                });
#pragma warning restore 612, 618
        }
    }
}
