// <auto-generated />
using System;
using HotelBooking.Modules.Inventory.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HotelBooking.Modules.Inventory.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260720145917_InitialInventory")]
    partial class InitialInventory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("inventory")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HotelBooking.Modules.Inventory.Domain.InventoryDates.InventoryDate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BookedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("booked_quantity");

                    b.Property<int>("ClosedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("closed_quantity");

                    b.Property<int>("HeldQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("held_quantity");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uuid")
                        .HasColumnName("hotel_id");

                    b.Property<DateOnly>("OccupiedDate")
                        .HasColumnType("date")
                        .HasColumnName("occupied_date");

                    b.Property<Guid>("RoomTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_type_id");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("total_quantity");

                    b.HasKey("Id")
                        .HasName("pk_inventory_dates");

                    b.HasIndex("HotelId", "RoomTypeId", "OccupiedDate")
                        .IsUnique()
                        .HasDatabaseName("ux_inventory_dates_hotel_id_room_type_id_occupied_date");

                    b.ToTable("inventory_dates", "inventory", t =>
                        {
                            t.HasCheckConstraint("ck_inventory_dates_committed_quantity_within_total", "held_quantity + booked_quantity + closed_quantity <= total_quantity");

                            t.HasCheckConstraint("ck_inventory_dates_quantities_non_negative", "total_quantity >= 0 AND held_quantity >= 0 AND booked_quantity >= 0 AND closed_quantity >= 0");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
